# Generated by Django 5.2.4 on 2025-07-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contact_remove_product_id_product_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('first_name', models.CharField(max_length=111)),
                ('last_name', models.CharField(max_length=111)),
                ('phone', models.CharField(max_length=111)),
                ('email', models.CharField(max_length=111)),
                ('address', models.CharField(max_length=111)),
                ('city', models.CharField(max_length=41)),
                ('district', models.CharField(max_length=21)),
                ('province', models.CharField(max_length=21)),
                ('zip_code', models.CharField(max_length=111)),
                ('payment_method', models.CharField(max_length=111)),
            ],
        ),
    ]
