# Generated by Django 5.2.4 on 2025-07-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_orders_city_remove_orders_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('first_name', models.CharField(max_length=111)),
                ('last_name', models.CharField(max_length=111)),
                ('phone', models.CharField(max_length=111)),
                ('email', models.CharField(max_length=111)),
                ('address', models.CharField(max_length=111)),
                ('province', models.CharField(max_length=51)),
                ('district', models.CharField(max_length=61)),
                ('zip_code', models.CharField(max_length=111)),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
