# Generated by Django 5.2.4 on 2025-07-22 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_updateorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='updateOrder',
            new_name='Orderupdate',
        ),
    ]
